version: "3"

services:
  web:
    image: nginx:1.26.2
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./logs:/var/log/nginx
